### ISSUE TITLE
Docs notebooks generate errors

### ISSUE THREAD

**Issue by bstellato** [stellatogrp/lropt#26]
The notebooks in the documentation generate errors. See, for example, [this link](https://stellatogrp.github.io/lropt/examples/experiments/tutorial_deterministic.html)

<img width="761" alt="Screen Shot 2023-05-08 at 10 42 08 AM" src="https://user-images.githubusercontent.com/5514200/236854212-eea36607-2e1e-4e1b-85c5-920c8106eb3a.png">

There are also several latex errors that need to be fixed
<img width="766" alt="Screen Shot 2023-05-08 at 10 42 21 AM" src="https://user-images.githubusercontent.com/5514200/236854264-5647540d-d730-4ac9-a9f7-819e045f769e.png">

**Comment by AmitSolomonPrinceton** [comment]
The link is broken (error 404). Is this issue still relevant?

**Comment by bstellato** [comment]
Not anymore. Let's pay attention when we create new notebooks for this.
