### ISSUE TITLE
Several test cases do not test anything

### ISSUE THREAD

**Issue by bstellato** [stellatogrp/lropt#29]
Several tests do not check for the output but just solve the problem or print the value. We need to add asserts to make sure the code does not return something stupid. See, for example:

https://github.com/stellatogrp/lropt/blob/61f04d9ddcc35281e1cab5493c4131067a2659af/tests/test_quad.py#L90-L96

**Comment by Irina526** [comment]
fixed

**Comment by Irina526** [comment]
fixed
